// This file is automatically generated by qtc from "rcroomsoffice365.qtpl".
// See https://github.com/valyala/quicktemplate for details.

//line rcroomsoffice365.qtpl:1
package rcroomsoffice365

//line rcroomsoffice365.qtpl:1
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line rcroomsoffice365.qtpl:1
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line rcroomsoffice365.qtpl:1
func StreamRingCentralRoomsOffice365(qw422016 *qt422016.Writer, data RingCentralRoomsOffice365Data) {
	//line rcroomsoffice365.qtpl:1
	qw422016.N().S(`
$UserCredential = Get-Credential 

`)
	//line rcroomsoffice365.qtpl:4
	if len(data.China) > 0 {
		//line rcroomsoffice365.qtpl:4
		qw422016.N().S(`
$Session = New-PSSession -ConfigurationName Microsoft.Exchange -ConnectionUri https://outlook.office365.com/powershell-liveid/ -Credential $UserCredential -Authentication Basic -AllowRedirection
`)
		//line rcroomsoffice365.qtpl:6
	} else {
		//line rcroomsoffice365.qtpl:6
		qw422016.N().S(`
$Session = New-PSSession -ConfigurationName Microsoft.Exchange -ConnectionUri https://partner.outlook.cn/powershell-liveid/ -Credential $UserCredential -Authentication Basic -AllowRedirection
`)
		//line rcroomsoffice365.qtpl:8
	}
	//line rcroomsoffice365.qtpl:8
	qw422016.N().S(`

Import-PSSession $Session

Set-ExecutionPolicy Unrestricted

Get-CalendarProcessing -Identity "`)
	//line rcroomsoffice365.qtpl:14
	qw422016.E().S(data.RoomName)
	//line rcroomsoffice365.qtpl:14
	qw422016.N().S(`" | Format-List identity,deletesubject,addorganizertosubject,RemovePrivateProperty

Set-CalendarProcessing "`)
	//line rcroomsoffice365.qtpl:16
	qw422016.E().S(data.RoomName)
	//line rcroomsoffice365.qtpl:16
	qw422016.N().S(`" -AddOrganizerToSubject $false -OrganizerInfo $true -DeleteAttachments $true -DeleteComments $false -DeleteSubject $false -RemovePrivateProperty $false

Get-CalendarProcessing -Identity "`)
	//line rcroomsoffice365.qtpl:18
	qw422016.E().S(data.RoomName)
	//line rcroomsoffice365.qtpl:18
	qw422016.N().S(`" | Format-List identity,deletesubject,addorganizertosubject,RemovePrivateProperty

Remove-PSSession $Session

`)
//line rcroomsoffice365.qtpl:22
}

//line rcroomsoffice365.qtpl:22
func WriteRingCentralRoomsOffice365(qq422016 qtio422016.Writer, data RingCentralRoomsOffice365Data) {
	//line rcroomsoffice365.qtpl:22
	qw422016 := qt422016.AcquireWriter(qq422016)
	//line rcroomsoffice365.qtpl:22
	StreamRingCentralRoomsOffice365(qw422016, data)
	//line rcroomsoffice365.qtpl:22
	qt422016.ReleaseWriter(qw422016)
//line rcroomsoffice365.qtpl:22
}

//line rcroomsoffice365.qtpl:22
func RingCentralRoomsOffice365(data RingCentralRoomsOffice365Data) string {
	//line rcroomsoffice365.qtpl:22
	qb422016 := qt422016.AcquireByteBuffer()
	//line rcroomsoffice365.qtpl:22
	WriteRingCentralRoomsOffice365(qb422016, data)
	//line rcroomsoffice365.qtpl:22
	qs422016 := string(qb422016.B)
	//line rcroomsoffice365.qtpl:22
	qt422016.ReleaseByteBuffer(qb422016)
	//line rcroomsoffice365.qtpl:22
	return qs422016
//line rcroomsoffice365.qtpl:22
}
